# Generated by Django 3.2 on 2022-02-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_dt', models.DateField(auto_now=True)),
                ('ored_name', models.CharField(max_length=200)),
                ('oder_phone', models.CharField(max_length=200)),
            ],
        ),
    ]
