# Generated by Django 3.2 on 2022-02-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='oder_phone',
            field=models.CharField(max_length=200, verbose_name='telefon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ored_name',
            field=models.CharField(max_length=200, verbose_name='ismi'),
        ),
    ]
