# Generated by Django 3.2 on 2022-02-21 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20220221_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ored_name',
            new_name='order_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='oder_phone',
            new_name='order_phone',
        ),
    ]
